version: '3.8'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=mysqltestdb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    platform: linux/x86_64

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"